In [1]:
import pandas as pd
import ezz

In [2]:
train_df = pd.read_csv('./house-prices-advanced-regression-techniques/train.csv')
test_df = pd.read_csv('./house-prices-advanced-regression-techniques/test.csv')

In [3]:
train_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
train_df['SalePrice'].isna().sum()

0

In [5]:
ez=ezz.colimp()
num_cols,cate_cols = ez.get_dum(train_df)

numerical(1st arg) and categorical(2nd arg) columns are differentiate

In [6]:
num_cols

['Id',
 'MSSubClass',
 'LotFrontage',
 'LotArea',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'MasVnrArea',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold',
 'SalePrice']

In [7]:
train_df[num_cols].corr()['SalePrice']

Id              -0.021917
MSSubClass      -0.084284
LotFrontage      0.351799
LotArea          0.263843
OverallQual      0.790982
OverallCond     -0.077856
YearBuilt        0.522897
YearRemodAdd     0.507101
MasVnrArea       0.477493
BsmtFinSF1       0.386420
BsmtFinSF2      -0.011378
BsmtUnfSF        0.214479
TotalBsmtSF      0.613581
1stFlrSF         0.605852
2ndFlrSF         0.319334
LowQualFinSF    -0.025606
GrLivArea        0.708624
BsmtFullBath     0.227122
BsmtHalfBath    -0.016844
FullBath         0.560664
HalfBath         0.284108
BedroomAbvGr     0.168213
KitchenAbvGr    -0.135907
TotRmsAbvGrd     0.533723
Fireplaces       0.466929
GarageYrBlt      0.486362
GarageCars       0.640409
GarageArea       0.623431
WoodDeckSF       0.324413
OpenPorchSF      0.315856
EnclosedPorch   -0.128578
3SsnPorch        0.044584
ScreenPorch      0.111447
PoolArea         0.092404
MiscVal         -0.021190
MoSold           0.046432
YrSold          -0.028923
SalePrice        1.000000
Name: SalePrice, dtype: float64

In [8]:
train_df[num_cols].isnull().sum()

Id                 0
MSSubClass         0
LotFrontage      259
LotArea            0
OverallQual        0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
MasVnrArea         8
BsmtFinSF1         0
BsmtFinSF2         0
BsmtUnfSF          0
TotalBsmtSF        0
1stFlrSF           0
2ndFlrSF           0
LowQualFinSF       0
GrLivArea          0
BsmtFullBath       0
BsmtHalfBath       0
FullBath           0
HalfBath           0
BedroomAbvGr       0
KitchenAbvGr       0
TotRmsAbvGrd       0
Fireplaces         0
GarageYrBlt       81
GarageCars         0
GarageArea         0
WoodDeckSF         0
OpenPorchSF        0
EnclosedPorch      0
3SsnPorch          0
ScreenPorch        0
PoolArea           0
MiscVal            0
MoSold             0
YrSold             0
SalePrice          0
dtype: int64

In [9]:
train_df[num_cols]= ez.impute_col(train_df,num_cols=num_cols)

Done!

In [10]:
train_df[num_cols].isna().sum()

Id               0
MSSubClass       0
LotFrontage      0
LotArea          0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
MasVnrArea       0
BsmtFinSF1       0
BsmtFinSF2       0
BsmtUnfSF        0
TotalBsmtSF      0
1stFlrSF         0
2ndFlrSF         0
LowQualFinSF     0
GrLivArea        0
BsmtFullBath     0
BsmtHalfBath     0
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
TotRmsAbvGrd     0
Fireplaces       0
GarageYrBlt      0
GarageCars       0
GarageArea       0
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
MiscVal          0
MoSold           0
YrSold           0
SalePrice        0
dtype: int64

In [11]:
train_df[cate_cols].isna().sum()

MSZoning            0
Street              0
Alley            1369
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
MasVnrType        872
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           37
BsmtCond           37
BsmtExposure       38
BsmtFinType1       37
BsmtFinType2       38
Heating             0
HeatingQC           0
CentralAir          0
Electrical          1
KitchenQual         0
Functional          0
FireplaceQu       690
GarageType         81
GarageFinish       81
GarageQual         81
GarageCond         81
PavedDrive          0
PoolQC           1453
Fence            1179
MiscFeature      1406
SaleType            0
SaleCondition       0
dtype: int64

In [12]:
drop_col=[]
for col in cate_cols:
    if (train_df[col].isna().sum())!=0:
        drop_col.append(col)

In [13]:
train_df['PoolQC'].fillna('na',inplace=True)

In [14]:
mdf=train_df.drop('PoolQC',axis=1)
max(mdf['SalePrice'])

755000.0

## dropping columns unnecessary columns

In [15]:
train_df.drop(['Id','PoolQC'],axis=1, inplace=True)
test_df.drop(['Id','PoolQC'],axis=1, inplace=True)

In [16]:
train_df.head(2)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60.0,RL,65.0,8450.0,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0.0,0.0,NaN,NaN,0.0,2.0,2008.0,WD,Normal,208500.0
1,20.0,RL,80.0,9600.0,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0.0,0.0,NaN,NaN,0.0,5.0,2007.0,WD,Normal,181500.0

In [17]:
train_df['MiscFeature'].value_counts()

MiscFeature
Shed    49
Gar2     2
Othr     2
TenC     1
Name: count, dtype: int64

In [18]:
train_df[train_df['MiscFeature']=='Othr']

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
705,190.0,RM,70.0,5600.0,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0.0,0.0,NaN,Othr,3500.0,7.0,2010.0,WD,Normal,55000.0
873,40.0,RL,60.0,12144.0,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0.0,0.0,NaN,Othr,0.0,9.0,2009.0,WD,Normal,133000.0

In [19]:
train_df.drop([1386,346,1230,705,873],inplace=True)

In [20]:
train_df

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60.0,RL,65.0,8450.0,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0.0,0.0,NaN,NaN,0.0,2.0,2008.0,WD,Normal,208500.0
1,20.0,RL,80.0,9600.0,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0.0,0.0,NaN,NaN,0.0,5.0,2007.0,WD,Normal,181500.0
2,60.0,RL,68.0,11250.0,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0.0,0.0,NaN,NaN,0.0,9.0,2008.0,WD,Normal,223500.0
3,70.0,RL,60.0,9550.0,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0.0,0.0,NaN,NaN,0.0,2.0,2006.0,WD,Abnorml,140000.0
4,60.0,RL,84.0,14260.0,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0.0,0.0,NaN,NaN,0.0,12.0,2008.0,WD,Normal,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60.0,RL,62.0,7917.0,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0.0,0.0,NaN,NaN,0.0,8.0,2007.0,WD,Normal,175000.0
1456,20.0,RL,85.0,13175.0,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0.0,0.0,MnPrv,NaN,0.0,2.0,2010.0,WD,Normal,210000.0
1457,70.0,RL,66.0,9042.0,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0.0,0.0,GdPrv,Shed,2500.0,5.0,2010.0,WD,Normal,266500.0
1458,20.0,RL,68.0,9717.0,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0.0,0.0,NaN,NaN,0.0,4.0,2010.0,WD,Normal,142125.0
1459,20.0,RL,75.0,9937.0,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0.0,0.0,NaN,NaN,0.0,6.0,2008.0,WD,Normal,147500.0

In [21]:
train_df.fillna('na',inplace=True)
train_df['Fence'].value_counts()

Fence
na       1175
MnPrv     156
GdPrv      59
GdWo       54
MnWw       11
Name: count, dtype: int64

In [22]:
def show_count(c):
    train_df[c].fillna('na', inplace=True)
    test_df[c].fillna('na', inplace=True)
    return train_df[c].value_counts()
def show_idx(c,val):
    df=train_df[train_df[c]==val]
    return list(df.index)

In [23]:
drop_col.remove('PoolQC')

In [24]:
for col in drop_col:
    print(show_count(col))

Alley
na      1364
Grvl      50
Pave      41
Name: count, dtype: int64
MasVnrType
na         868
BrkFace    444
Stone      128
BrkCmn      15
Name: count, dtype: int64
BsmtQual
TA    647
Gd    616
Ex    121
na     36
Fa     35
Name: count, dtype: int64
BsmtCond
TA    1307
Gd      65
Fa      45
na      36
Po       2
Name: count, dtype: int64
BsmtExposure
No    950
Av    221
Gd    134
Mn    113
na     37
Name: count, dtype: int64
BsmtFinType1
Unf    430
GLQ    417
ALQ    220
BLQ    146
Rec    132
LwQ     74
na      36
Name: count, dtype: int64
BsmtFinType2
Unf    1254
Rec      53
LwQ      45
na       37
BLQ      33
ALQ      19
GLQ      14
Name: count, dtype: int64
Electrical
SBrkr    1329
FuseA      94
FuseF      27
FuseP       3
Mix         1
na          1
Name: count, dtype: int64
FireplaceQu
na    688
Gd    379
TA    311
Fa     33
Ex     24
Po     20
Name: count, dtype: int64
GarageType
Attchd     867
Detchd     387
BuiltIn     87
na          80
Basment     19
CarPort      9
2Types       6
Name: count, dtype: int64
GarageFinish
Unf    604
RFn    419
Fin    352
na      80
Name: count, dtype: int64
GarageQual
TA    1307
na      80
Fa      48
Gd      14
Ex       3
Po       3
Name: count, dtype: int64
GarageCond
TA    1322
na      80
Fa      35
Gd       9
Po       7
Ex       2
Name: count, dtype: int64
Fence
na       1175
MnPrv     156
GdPrv      59
GdWo       54
MnWw       11
Name: count, dtype: int64
MiscFeature
na      1406
Shed      49
Name: count, dtype: int64

In [25]:
idx_drop=[]

In [26]:
train_df[train_df['BsmtCond']=='Po']

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
375,30.0,RL,70.049958,10020.0,Pave,na,IR1,Low,AllPub,Inside,...,0.0,0.0,na,na,0.0,3.0,2009.0,WD,Normal,61000.0
398,30.0,RM,60.000000,8967.0,Pave,na,Reg,Lvl,AllPub,Corner,...,0.0,0.0,na,na,0.0,11.0,2007.0,WD,Abnorml,67000.0

In [27]:
idx_drop.extend([375, 398])
idx_drop

[375, 398]

In [28]:
idx_drop.extend(show_idx('Electrical','Mix'))
idx_drop.extend(show_idx('Electrical','FuseP'))
idx_drop.extend(show_idx('Electrical','na'))
idx_drop.extend(show_idx('GarageType','CarPort'))
idx_drop.extend(show_idx('GarageType','2Types'))
idx_drop.extend(show_idx('GarageQual','Ex'))
idx_drop.extend(show_idx('GarageQual','Po'))
idx_drop.extend(show_idx('GarageCond','Gd'))
idx_drop.extend(show_idx('GarageCond','Po'))
idx_drop.extend(show_idx('GarageCond','Ex'))

In [29]:
len(idx_drop)

46

In [30]:
train_df.drop(idx_drop,inplace=True)
train_df

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60.0,RL,65.0,8450.0,Pave,na,Reg,Lvl,AllPub,Inside,...,0.0,0.0,na,na,0.0,2.0,2008.0,WD,Normal,208500.0
1,20.0,RL,80.0,9600.0,Pave,na,Reg,Lvl,AllPub,FR2,...,0.0,0.0,na,na,0.0,5.0,2007.0,WD,Normal,181500.0
2,60.0,RL,68.0,11250.0,Pave,na,IR1,Lvl,AllPub,Inside,...,0.0,0.0,na,na,0.0,9.0,2008.0,WD,Normal,223500.0
3,70.0,RL,60.0,9550.0,Pave,na,IR1,Lvl,AllPub,Corner,...,0.0,0.0,na,na,0.0,2.0,2006.0,WD,Abnorml,140000.0
4,60.0,RL,84.0,14260.0,Pave,na,IR1,Lvl,AllPub,FR2,...,0.0,0.0,na,na,0.0,12.0,2008.0,WD,Normal,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60.0,RL,62.0,7917.0,Pave,na,Reg,Lvl,AllPub,Inside,...,0.0,0.0,na,na,0.0,8.0,2007.0,WD,Normal,175000.0
1456,20.0,RL,85.0,13175.0,Pave,na,Reg,Lvl,AllPub,Inside,...,0.0,0.0,MnPrv,na,0.0,2.0,2010.0,WD,Normal,210000.0
1457,70.0,RL,66.0,9042.0,Pave,na,Reg,Lvl,AllPub,Inside,...,0.0,0.0,GdPrv,Shed,2500.0,5.0,2010.0,WD,Normal,266500.0
1458,20.0,RL,68.0,9717.0,Pave,na,Reg,Lvl,AllPub,Inside,...,0.0,0.0,na,na,0.0,4.0,2010.0,WD,Normal,142125.0
1459,20.0,RL,75.0,9937.0,Pave,na,Reg,Lvl,AllPub,Inside,...,0.0,0.0,na,na,0.0,6.0,2008.0,WD,Normal,147500.0

In [31]:
C = cate_cols
C.remove('PoolQC')
idx_drop2=[]
for col in C:
    print(show_count(col))

MSZoning
RL         1122
RM          207
FV           65
RH           14
C (all)       9
Name: count, dtype: int64
Street
Pave    1413
Grvl       4
Name: count, dtype: int64
Alley
na      1331
Grvl      45
Pave      41
Name: count, dtype: int64
LotShape
Reg    896
IR1    473
IR2     39
IR3      9
Name: count, dtype: int64
LandContour
Lvl    1276
Bnk      59
HLS      49
Low      33
Name: count, dtype: int64
Utilities
AllPub    1416
NoSeWa       1
Name: count, dtype: int64
LotConfig
Inside     1020
Corner      257
CulDSac      90
FR2          46
FR3           4
Name: count, dtype: int64
LandSlope
Gtl    1345
Mod      60
Sev      12
Name: count, dtype: int64
Neighborhood
NAmes      216
CollgCr    150
OldTown    105
Edwards     95
Somerst     86
Gilbert     79
NridgHt     77
NWAmes      72
Sawyer      71
SawyerW     57
BrkSide     57
Crawfor     49
Mitchel     47
NoRidge     40
Timber      35
IDOTRR      32
ClearCr     28
StoneBr     25
SWISU       24
MeadowV     17
Blmngtn     17
BrDale      16
Veenker     11
NPkVill      9
Blueste      2
Name: count, dtype: int64
Condition1
Norm      1227
Feedr       78
Artery      43
RRAn        25
PosN        19
RRAe        11
PosA         8
RRNn         4
RRNe         2
Name: count, dtype: int64
Condition2
Norm      1404
Feedr        6
RRNn         2
PosN         2
Artery       1
PosA         1
RRAn         1
Name: count, dtype: int64
BldgType
1Fam      1189
TwnhsE     114
Duplex      44
Twnhs       43
2fmCon      27
Name: count, dtype: int64
HouseStyle
1Story    706
2Story    434
1.5Fin    152
SLvl       62
SFoyer     35
1.5Unf     12
2.5Unf     10
2.5Fin      6
Name: count, dtype: int64
RoofStyle
Gable      1110
Hip         277
Gambrel      11
Flat         11
Mansard       7
Shed          1
Name: count, dtype: int64
RoofMatl
CompShg    1394
Tar&Grv       9
WdShngl       5
WdShake       5
Metal         1
Membran       1
Roll          1
ClyTile       1
Name: count, dtype: int64
Exterior1st
VinylSd    510
HdBoard    214
MetalSd    212
Wd Sdng    194
Plywood    102
CemntBd     61
BrkFace     50
WdShing     26
Stucco      25
AsbShng     16
BrkComm      2
Stone        2
AsphShn      1
ImStucc      1
CBlock       1
Name: count, dtype: int64
Exterior2nd
VinylSd    500
MetalSd    206
HdBoard    199
Wd Sdng    187
Plywood    135
CmentBd     60
Wd Shng     36
BrkFace     25
Stucco      25
AsbShng     17
ImStucc     10
Brk Cmn      7
Stone        5
AsphShn      3
Other        1
CBlock       1
Name: count, dtype: int64
MasVnrType
na         841
BrkFace    437
Stone      126
BrkCmn      13
Name: count, dtype: int64
ExterQual
TA    873
Gd    482
Ex     52
Fa     10
Name: count, dtype: int64
ExterCond
TA    1251
Gd     139
Fa      23
Ex       3
Po       1
Name: count, dtype: int64
Foundation
PConc     642
CBlock    609
BrkTil    137
Slab       21
Stone       5
Wood        3
Name: count, dtype: int64
BsmtQual
TA    628
Gd    608
Ex    120
na     33
Fa     28
Name: count, dtype: int64
BsmtCond
TA    1280
Gd      64
Fa      40
na      33
Name: count, dtype: int64
BsmtExposure
No    926
Av    217
Gd    130
Mn    110
na     34
Name: count, dtype: int64
BsmtFinType1
GLQ    415
Unf    414
ALQ    217
BLQ    140
Rec    126
LwQ     72
na      33
Name: count, dtype: int64
BsmtFinType2
Unf    1226
Rec      50
LwQ      44
na       34
BLQ      32
ALQ      18
GLQ      13
Name: count, dtype: int64
Heating
GasA     1388
GasW       17
Grav        5
Wall        4
OthW        2
Floor       1
Name: count, dtype: int64
HeatingQC
Ex    732
TA    409
Gd    230
Fa     45
Po      1
Name: count, dtype: int64
CentralAir
Y    1334
N      83
Name: count, dtype: int64
Electrical
SBrkr    1302
FuseA      89
FuseF      26
Name: count, dtype: int64
KitchenQual
TA    705
Gd    581
Ex     97
Fa     34
Name: count, dtype: int64
Functional
Typ     1323
Min2      33
Min1      30
Mod       14
Maj1      13
Maj2       4
Name: count, dtype: int64
FireplaceQu
na    662
Gd    375
TA    306
Fa     32
Ex     23
Po     19
Name: count, dtype: int64
GarageType
Attchd     860
Detchd     374
BuiltIn     86
na          78
Basment     19
Name: count, dtype: int64
GarageFinish
Unf    579
RFn    412
Fin    348
na      78
Name: count, dtype: int64
GarageQual
TA    1288
na      78
Fa      41
Gd      10
Name: count, dtype: int64
GarageCond
TA    1306
na      78
Fa      33
Name: count, dtype: int64
PavedDrive
Y    1308
N      81
P      28
Name: count, dtype: int64
Fence
na       1149
MnPrv     150
GdWo       54
GdPrv      54
MnWw       10
Name: count, dtype: int64
MiscFeature
na      1371
Shed      46
Name: count, dtype: int64
SaleType
WD       1225
New       122
COD        42
ConLD       9
ConLI       5
ConLw       5
CWD         4
Oth         3
Con         2
Name: count, dtype: int64
SaleCondition
Normal     1165
Partial     125
Abnorml      95
Family       19
Alloca       10
AdjLand       3
Name: count, dtype: int64

## Dropping which has only less than 5 entries in dataset these points often leads a outlier and cause some inaccuracy in our model

In [32]:
idx_drop2.extend(show_idx('Street','Grvl'))
idx_drop2.extend(show_idx('Utilities','NoSeWa'))
idx_drop2.extend(show_idx('LotConfig','FR3'))
idx_drop2.extend(show_idx('Neighborhood','Blueste'))
idx_drop2.extend(show_idx('Condition1','RRNn'))
idx_drop2.extend(show_idx('Condition1','RRNe'))
idx_drop2.extend(show_idx('Condition2','RRNn'))
idx_drop2.extend(show_idx('Condition2','PosN'))
idx_drop2.extend(show_idx('Condition2','Artery'))
idx_drop2.extend(show_idx('Condition2','PosA'))
idx_drop2.extend(show_idx('Condition2','RRAn'))
idx_drop2.extend(show_idx('LotConfig','FR3'))
idx_drop2.extend(show_idx('HouseStyle','2.5Fin'))
idx_drop2.extend(show_idx('RoofStyle','Shed'))
idx_drop2.extend(show_idx('RoofMatl','Metal'))
idx_drop2.extend(show_idx('RoofMatl','Membran'))
idx_drop2.extend(show_idx('RoofMatl','Roll'))
idx_drop2.extend(show_idx('RoofMatl','ClyTile'))
idx_drop2.extend(show_idx('Exterior1st','BrkComm'))
idx_drop2.extend(show_idx('Exterior1st','Stone'))
idx_drop2.extend(show_idx('Exterior1st','AsphShn'))
idx_drop2.extend(show_idx('Exterior1st','ImStucc'))
idx_drop2.extend(show_idx('Exterior1st','CBlock'))
idx_drop2.extend(show_idx('Exterior2nd','AsphShn'))
idx_drop2.extend(show_idx('Exterior2nd','Other'))
idx_drop2.extend(show_idx('Exterior2nd','CBlock'))
idx_drop2.extend(show_idx('ExterCond','Ex'))
idx_drop2.extend(show_idx('ExterCond','Po'))
idx_drop2.extend(show_idx('Foundation','Wood'))
idx_drop2.extend(show_idx('Heating','Wall'))
idx_drop2.extend(show_idx('Heating','OthW'))
idx_drop2.extend(show_idx('Heating','Floor'))
idx_drop2.extend(show_idx('HeatingQC','Po'))
idx_drop2.extend(show_idx('Functional', 'Maj2'))
idx_drop2.extend(show_idx('SaleType', 'CWD'))
idx_drop2.extend(show_idx('SaleType', 'Oth'))
idx_drop2.extend(show_idx('SaleType', 'Con'))
idx_drop2.extend(show_idx('SaleCondition', 'AdjLand'))

In [33]:
train_df.drop(idx_drop2, inplace=True)
train_df

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60.0,RL,65.0,8450.0,Pave,na,Reg,Lvl,AllPub,Inside,...,0.0,0.0,na,na,0.0,2.0,2008.0,WD,Normal,208500.0
1,20.0,RL,80.0,9600.0,Pave,na,Reg,Lvl,AllPub,FR2,...,0.0,0.0,na,na,0.0,5.0,2007.0,WD,Normal,181500.0
2,60.0,RL,68.0,11250.0,Pave,na,IR1,Lvl,AllPub,Inside,...,0.0,0.0,na,na,0.0,9.0,2008.0,WD,Normal,223500.0
3,70.0,RL,60.0,9550.0,Pave,na,IR1,Lvl,AllPub,Corner,...,0.0,0.0,na,na,0.0,2.0,2006.0,WD,Abnorml,140000.0
4,60.0,RL,84.0,14260.0,Pave,na,IR1,Lvl,AllPub,FR2,...,0.0,0.0,na,na,0.0,12.0,2008.0,WD,Normal,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60.0,RL,62.0,7917.0,Pave,na,Reg,Lvl,AllPub,Inside,...,0.0,0.0,na,na,0.0,8.0,2007.0,WD,Normal,175000.0
1456,20.0,RL,85.0,13175.0,Pave,na,Reg,Lvl,AllPub,Inside,...,0.0,0.0,MnPrv,na,0.0,2.0,2010.0,WD,Normal,210000.0
1457,70.0,RL,66.0,9042.0,Pave,na,Reg,Lvl,AllPub,Inside,...,0.0,0.0,GdPrv,Shed,2500.0,5.0,2010.0,WD,Normal,266500.0
1458,20.0,RL,68.0,9717.0,Pave,na,Reg,Lvl,AllPub,Inside,...,0.0,0.0,na,na,0.0,4.0,2010.0,WD,Normal,142125.0
1459,20.0,RL,75.0,9937.0,Pave,na,Reg,Lvl,AllPub,Inside,...,0.0,0.0,na,na,0.0,6.0,2008.0,WD,Normal,147500.0

# ok so outliers has been removed successfully now let's convert data's which has 10 unique values as object dtype to integer or floating point dtype

In [34]:
col_to_conv = [col for col in train_df.columns if train_df[col].nunique() <= 10 and train_df[col].dtype == 'object']
len(col_to_conv)

40

In [35]:
def conv_col(col):
    count = 0 
    k = list(train_df[col].unique())
    Dict = {k[i]: count + i for i in range(len(k))}
    df = train_df[col].replace(Dict)
    return df
def conv_col1(col):
    count = 0 
    k = list(test_df[col].unique())
    Dict = {k[i]: count + i for i in range(len(k))}
    df_test = test_df[col].replace(Dict)
    return df_test

modified_train = pd.DataFrame(map(conv_col,col_to_conv)).T
modified_test= pd.DataFrame(map(conv_col1,col_to_conv)).T

In [36]:
modified_test

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Condition1,Condition2,...,FireplaceQu,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,Fence,MiscFeature,SaleType,SaleCondition
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,1,0,0,1,0,1,0,...,0,0,0,0,0,0,1,1,0,0
2,1,0,0,1,0,0,0,0,1,0,...,1,0,1,0,0,0,0,0,0,0
3,1,0,0,1,0,0,0,0,1,0,...,2,0,1,0,0,0,1,0,0,0
4,1,0,0,1,1,0,0,0,1,0,...,0,0,2,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2,0,0,0,0,0,0,0,1,0,...,0,3,3,1,1,0,1,0,0,0
1455,2,0,0,0,0,0,0,0,1,0,...,0,6,0,0,0,0,1,0,0,2
1456,1,0,0,0,0,0,0,0,1,0,...,1,1,0,0,0,0,1,0,0,2
1457,1,0,0,0,0,0,0,0,1,0,...,0,3,3,1,1,0,0,2,0,0
1458,1,0,0,0,0,0,0,1,1,0,...,1,0,1,0,0,0,1,0,0,0

In [37]:
modified_train.dtypes

MSZoning         int64
Street           int64
Alley            int64
LotShape         int64
LandContour      int64
Utilities        int64
LotConfig        int64
LandSlope        int64
Condition1       int64
Condition2       int64
BldgType         int64
HouseStyle       int64
RoofStyle        int64
RoofMatl         int64
Exterior1st      int64
MasVnrType       int64
ExterQual        int64
ExterCond        int64
Foundation       int64
BsmtQual         int64
BsmtCond         int64
BsmtExposure     int64
BsmtFinType1     int64
BsmtFinType2     int64
Heating          int64
HeatingQC        int64
CentralAir       int64
Electrical       int64
KitchenQual      int64
Functional       int64
FireplaceQu      int64
GarageType       int64
GarageFinish     int64
GarageQual       int64
GarageCond       int64
PavedDrive       int64
Fence            int64
MiscFeature      int64
SaleType         int64
SaleCondition    int64
dtype: object

In [38]:
modified_train_df = train_df.copy()
modified_test_df = test_df.copy()
modified_cols = modified_test.columns
modified_train_df.update(modified_train)
modified_test_df.update(modified_test)

In [39]:
modified_cols

Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'MasVnrType',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu',
       'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive',
       'Fence', 'MiscFeature', 'SaleType', 'SaleCondition'],
      dtype='object')

In [40]:
modified_test_df['MSZoning'].value_counts()

MSZoning
1    1114
2     242
3      74
4      15
0      10
5       4
Name: count, dtype: int64

In [41]:
modified_train_df[modified_cols] = modified_train_df[modified_cols].apply(pd.to_numeric)
modified_test_df[modified_cols] = modified_test_df[modified_cols].apply(pd.to_numeric)

In [42]:
num_cols = modified_train_df.select_dtypes(include=['int','float']).columns
cate_cols = modified_train_df.select_dtypes(include=['object']).columns

In [43]:
modified_train_df['Condition2'].value_counts()

Condition2
0    1338
1       5
Name: count, dtype: int64

In [44]:
len(list(modified_cols)),len(num_cols),train_df.shape,test_df.shape

(40, 77, (1343, 79), (1459, 78))

## SO far our conversion and deal with missing values is done now let's  figure out the scaling columns and let's scale them

In [45]:
sum(list(modified_train_df[num_cols].isna().sum()))

0

In [46]:
from functools import reduce
def extract_scale_cols(df,cols):
    ex_list=[]
    def Sum(a,b):
        return a+b
    def find_col(cols):
        l=list(df[cols])
        res = reduce(Sum,l[:10])
        return res>=100
    ex_list=list(filter(find_col,cols))
    return ex_list

In [47]:
extract_cols = extract_scale_cols(modified_train_df,num_cols)
extract_cols.remove('SalePrice')

In [48]:
modified_train_df[extract_cols] = ez.scale(modified_train_df,extract_cols)
modified_test_df[extract_cols] = ez.scale(modified_test_df,extract_cols)

In [49]:
modified_train_df[extract_cols]

,MSSubClass,LotFrontage,LotArea,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,GrLivArea,GarageYrBlt,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,MiscVal,YrSold
0,0.235294,0.150685,0.032619,0.948148,0.883333,0.122500,0.322669,0.064212,0.266999,0.180373,0.413559,0.332207,0.936364,0.394245,0.000000,0.111517,0.000000,0.0,0.50
1,0.000000,0.202055,0.037999,0.748148,0.433333,0.000000,0.446984,0.121575,0.393637,0.320663,0.000000,0.224046,0.690909,0.330935,0.347725,0.000000,0.000000,0.0,0.25
2,0.235294,0.160959,0.045718,0.933333,0.866667,0.101250,0.222121,0.185788,0.286962,0.202488,0.419370,0.350555,0.918182,0.437410,0.000000,0.076782,0.000000,0.0,0.50
3,0.294118,0.133562,0.037765,0.296296,0.333333,0.000000,0.098720,0.231164,0.235808,0.216655,0.366102,0.333897,0.890909,0.461871,0.000000,0.063985,0.492754,0.0,0.00
4,0.235294,0.215753,0.059798,0.925926,0.833333,0.218750,0.299360,0.209760,0.357143,0.280235,0.509927,0.450024,0.909091,0.601439,0.224037,0.153565,0.000000,0.0,0.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,0.235294,0.140411,0.030126,0.918519,0.833333,0.000000,0.000000,0.407962,0.297255,0.213891,0.336077,0.316997,0.900000,0.330935,0.000000,0.073126,0.000000,0.0,0.25
1456,0.000000,0.219178,0.054723,0.762963,0.633333,0.074375,0.361060,0.252140,0.480973,0.600898,0.000000,0.419845,0.709091,0.359712,0.407235,0.000000,0.000000,0.0,1.00
1457,0.294118,0.154110,0.035389,0.488889,0.933333,0.000000,0.125686,0.375428,0.359326,0.295093,0.557869,0.484307,0.372727,0.181295,0.000000,0.109689,0.000000,1.0,1.00
1458,0.000000,0.160959,0.038546,0.555556,0.766667,0.000000,0.022395,0.000000,0.336245,0.257084,0.000000,0.179623,0.454545,0.172662,0.427071,0.000000,0.202899,0.0,1.00
1459,0.000000,0.184932,0.039576,0.666667,0.250000,0.000000,0.379342,0.058219,0.391765,0.318590,0.000000,0.222598,0.590909,0.198561,0.858810,0.124314,0.000000,0.0,0.50

### Now the scaling has been done successfully now let's make the dummy or onehotencoding columns of  categorical columns

In [50]:
cate_cols

Index(['Neighborhood', 'Exterior2nd'], dtype='object')

In [51]:
modified_train_df['Exterior2nd'].value_counts()

Exterior2nd
VinylSd    488
HdBoard    192
MetalSd    189
Wd Sdng    179
Plywood    128
CmentBd     57
Wd Shng     35
BrkFace     23
Stucco      21
AsbShng     15
ImStucc      8
Brk Cmn      5
Stone        3
Name: count, dtype: int64

In [52]:
modified_test_df['Exterior2nd'].value_counts()

Exterior2nd
VinylSd    510
MetalSd    233
HdBoard    199
Wd Sdng    194
Plywood    128
CmentBd     66
Wd Shng     43
BrkFace     22
Stucco      21
AsbShng     18
Brk Cmn     15
ImStucc      5
CBlock       2
AsphShn      1
na           1
Stone        1
Name: count, dtype: int64

In [53]:
modified_train_df.drop(show_idx('Exterior2nd','Stone'),inplace=True)
modified_test_df.drop(show_idx('Exterior2nd','Stone'),inplace=True)

In [54]:
train_dum_df = ez.make_dum(modified_train_df,dum_cols = ['Neighborhood', 'Exterior2nd'], concat=True)
test_dum_df = ez.make_dum(modified_test_df,dum_cols = ['Neighborhood', 'Exterior2nd'], concat=True)

In [55]:
train_dum_df.head(3)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,Exterior2nd_BrkFace,Exterior2nd_CmentBd,Exterior2nd_HdBoard,Exterior2nd_ImStucc,Exterior2nd_MetalSd,Exterior2nd_Plywood,Exterior2nd_Stucco,Exterior2nd_VinylSd,Exterior2nd_Wd Sdng,Exterior2nd_Wd Shng
0,0.235294,0,0.150685,0.032619,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,0.000000,0,0.202055,0.037999,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
2,0.235294,0,0.160959,0.045718,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [56]:
test_dum_df.head(3)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,Exterior2nd_HdBoard,Exterior2nd_ImStucc,Exterior2nd_MetalSd,Exterior2nd_Plywood,Exterior2nd_Stone,Exterior2nd_Stucco,Exterior2nd_VinylSd,Exterior2nd_Wd Sdng,Exterior2nd_Wd Shng,Exterior2nd_na
0,0.000000,0,0.329609,0.184147,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,0.000000,1,0.335196,0.232124,0,0,1,0,0,1,...,0,0,0,0,0,0,0,1,0,0
2,0.235294,1,0.296089,0.224197,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0

### Making x and y

In [57]:
X = train_dum_df.drop('SalePrice',axis=1)
y = train_dum_df['SalePrice']

In [58]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,)

In [59]:
X_train

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,Exterior2nd_BrkFace,Exterior2nd_CmentBd,Exterior2nd_HdBoard,Exterior2nd_ImStucc,Exterior2nd_MetalSd,Exterior2nd_Plywood,Exterior2nd_Stucco,Exterior2nd_VinylSd,Exterior2nd_Wd Sdng,Exterior2nd_Wd Shng
1304,0.823529,1,0.037671,0.008823,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1141,0.235294,0,0.167979,0.041292,0,0,1,0,0,3,...,0,0,0,0,0,1,0,0,0,0
1280,0.000000,0,0.157534,0.038972,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
463,0.294118,0,0.181507,0.049170,0,0,1,3,0,0,...,0,0,0,0,0,0,1,0,0,0
73,0.000000,0,0.219178,0.040806,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,0.000000,0,0.167979,0.048468,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1168,0.294118,0,0.339041,0.057310,0,0,0,0,0,2,...,0,0,0,0,0,0,1,0,0,0
547,0.382353,0,0.113014,0.026978,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
319,0.352941,0,0.167979,0.059120,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1202,0.176471,1,0.099315,0.021158,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,1,0

## So far we done our Data cleaning,
                                     Now we have to build a Model let's try different models!

let's implement cross-validation and see how good our linearrgression model is

In [60]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.linear_model import LinearRegression,SGDRegressor, ElasticNet, Lasso,Ridge
import numpy as np
linreg = LinearRegression()

In [61]:
kf = KFold(n_splits=5, shuffle=True)
cvscores = cross_val_score(linreg, X,y,cv=kf)
print('cross-val scores', cvscores)
print('mean cross-val scores', np.mean(cvscores))
linear_models = [LinearRegression(),SGDRegressor(), ElasticNet(), Lasso(),Ridge()]

cross-val scores [0.88918596 0.89307471 0.90414554 0.88644305 0.88100987]
mean cross-val scores 0.8907718265666164

In [62]:
def cv(model):
    kf = KFold(n_splits=5, shuffle=True)
    cvscores = cross_val_score(model, X,y,cv=kf)
    print('cross-val scores', cvscores)
    print('mean cross-val scores\n', np.mean(cvscores))

In [63]:
for model in linear_models:
    cv(model)

cross-val scores [0.90206685 0.85822697 0.88151543 0.9151735  0.88913495]
mean cross-val scores
 0.8892235406811899
cross-val scores [-3.48695347e+16 -4.12970548e+16 -4.14651472e+17 -7.72367530e+17
 -1.99985491e+18]
mean cross-val scores
 -6.526081005492396e+17
cross-val scores [0.76051818 0.83375972 0.75002629 0.75551317 0.75059507]
mean cross-val scores
 0.7700824852158387

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.627e+11, tolerance: 6.682e+08
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.702e+11, tolerance: 6.589e+08
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.555e+11, tolerance: 6.981e+08
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.437e+11, tolerance: 6.432e+08
  model = cd_fast.enet_coordinate_descent(

cross-val scores [0.88892825 0.91282582 0.85795661 0.88857968 0.87713223]
mean cross-val scores
 0.885084517891849
cross-val scores [0.89397063 0.8982168  0.87457634 0.9129447  0.88418562]
mean cross-val scores
 0.892778819546877

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.775e+11, tolerance: 7.027e+08
  model = cd_fast.enet_coordinate_descent(

In [64]:
from sklearn.tree import DecisionTreeRegressor
tree = DecisionTreeRegressor(max_depth=30,random_state=42,min_samples_leaf=10)

In [65]:
def maxdepth(m):
    model = DecisionTreeRegressor(min_samples_leaf=10,max_depth=m)
    cvscores = cross_val_score(model, X,y,cv=kf)
    return np.mean(cvscores)

In [66]:
err_df = pd.DataFrame({'CV mean error':[maxdepth(i) for i in range(1,36)]})

In [67]:
err_df
# maxdepth=30

    CV mean error
0        0.454845
1        0.611848
2        0.683806
3        0.760715
4        0.721427
5        0.780328
6        0.797040
7        0.758380
8        0.774104
9        0.782346
10       0.792558
11       0.770005
12       0.777650
13       0.806356
14       0.807153
15       0.780430
16       0.780300
17       0.786967
18       0.805599
19       0.775914
20       0.764739
21       0.788719
22       0.792005
23       0.796742
24       0.789336
25       0.767183
26       0.785150
27       0.791249
28       0.788764
29       0.791322
30       0.774788
31       0.779088
32       0.760971
33       0.806054
34       0.793257

In [68]:
from sklearn.ensemble import RandomForestRegressor

In [69]:
rf = RandomForestRegressor(n_jobs=-1,max_depth=20,random_state=42,n_estimators=40)

In [70]:
cv(rf)

cross-val scores [0.89271166 0.88125987 0.91000271 0.85750937 0.90884158]
mean cross-val scores
 0.8900650361778455

In [71]:
from sklearn.svm import SVR

In [72]:
svr = SVR(C=1,kernel='rbf', gamma='auto')

In [73]:
cv(svr)

cross-val scores [-0.10757324 -0.0375149  -0.03252765 -0.02086584 -0.08055359]
mean cross-val scores
 -0.05580704342008667

In [74]:
from xgboost import XGBRegressor
import xgboost

In [75]:
xgb = XGBRegressor(n_jobs=-1,random_state=42, n_estimators=150)

In [76]:
cv(xgb)

cross-val scores [0.88395708 0.8552292  0.88740833 0.88613989 0.88720691]
mean cross-val scores
 0.8799882796667603

## Random tuning the hyperparameter can change the accuracy by a noticeable amount let's try grid search cv from sklearn library

In [77]:
from sklearn.model_selection import GridSearchCV
reg = GridSearchCV(svr,{'C':[0.8,0.9,1,2,3], 'kernel':['rbf', 'linear']}, cv=kf, return_train_score=False)
reg.fit(X_train,y_train)
score_df = pd.DataFrame(reg.cv_results_)

In [78]:
score_df[['param_C','param_kernel','mean_test_score']]

  param_C param_kernel  mean_test_score
0     0.8          rbf        -0.063698
1     0.8       linear        -0.003889
2     0.9          rbf        -0.063657
3     0.9       linear         0.003144
4       1          rbf        -0.063616
5       1       linear         0.008709
6       2          rbf        -0.063205
7       2       linear         0.076222
8       3          rbf        -0.062795
9       3       linear         0.138020

## Let's try linear models,xgboost and randomforest in gridsearchcv

In [79]:
model_params={
    'lin_reg':{
        'model':LinearRegression(),
        'params':{
            'copy_X':[True,False],
            'fit_intercept':[True,False]
        }
    },
    'rf':{
        'model': RandomForestRegressor(random_state=42,n_jobs=-1),
        'params':{
            'n_estimators':[50,100,150],
            'criterion':['friedman_mse', 'absolute_error'],
            'max_depth':[10,20,30],
            'min_samples_split': [1,2,3],
            'min_samples_leaf':[1,2,3],
            'bootstrap':[True,False]
            
        }
    },
    'xgb':{
        'model':XGBRegressor(random_state=42,n_jobs=-1),
        'params':{
        'n_estimators':[50,100,150],
        'learning_rate':[0.01,0.9,1,2],
        'device':['cuda:0'],
    }
},
}

In [80]:
model_param2={
    'lin_reg':{
        'model':LinearRegression(),
        'params':{
            'copy_X':[True,False],
            'fit_intercept':[True,False]
        }
    },
    'xgb':{
        'model':XGBRegressor(random_state=42,n_jobs=-1),
        'params':{
        'n_estimators':[150,200,250],
        'learning_rate':[0.01,0.7,0.9],
        'device':['cuda:0'],
        'max_leaves':[0,1,2,3],   
    }
},
}

In [81]:
scores = []

for model_name, mp in model_param2.items():
    reg =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    reg.fit(X_train,y_train)
    scores.append({
        'model': model_name,
        'best_score': reg.best_score_,
        'best_params': reg.best_params_
    })
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

/usr/local/lib/python3.8/dist-packages/xgboost/core.py:160: UserWarning: [09:05:41] WARNING: /workspace/src/common/error_msg.cc:58: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  warnings.warn(smsg, UserWarning)

     model  best_score                                        best_params
0  lin_reg    0.894691            {'copy_X': True, 'fit_intercept': True}
1      xgb    0.894907  {'device': 'cuda:0', 'learning_rate': 0.7, 'ma...

## After seeing gridsearchcv we see xgboost performs better with little less about 90% so by selecting the xgboost let's conclude our model searching

In [82]:
for name,mod in df['best_params'].items():
    print(mod)

{'copy_X': True, 'fit_intercept': True}
{'device': 'cuda:0', 'learning_rate': 0.7, 'max_leaves': 2, 'n_estimators': 250}

In [83]:
best_estimator=reg.best_estimator_

## Let's make a prediction function which will clean the data for us

## Sample submission

In [84]:
submission_df = pd.read_csv('./house-prices-advanced-regression-techniques/sample_submission.csv')
submission_df

        Id      SalePrice
0     1461  169277.052498
1     1462  187758.393989
2     1463  183583.683570
3     1464  179317.477511
4     1465  150730.079977
...    ...            ...
1454  2915  167081.220949
1455  2916  164788.778231
1456  2917  219222.423400
1457  2918  184924.279659
1458  2919  187741.866657

[1459 rows x 2 columns]

In [85]:
test_dum_df.shape

(1456, 115)

In [86]:
test_dum_df.drop(['Exterior2nd_CBlock', 'Exterior2nd_Stone', 'Neighborhood_Blueste', 'Exterior2nd_AsphShn', 'Exterior2nd_na'], axis=1,inplace=True)

In [87]:
test_preds = best_estimator.predict(test_dum_df)
test_preds_df = pd.DataFrame(test_preds, columns=['SalePrice'])

In [88]:
test_preds_df

          SalePrice
0     145064.734375
1     192433.062500
2     193111.343750
3     201146.484375
4     222493.656250
...             ...
1451   62125.687500
1452   76648.296875
1453  208723.484375
1454  156292.812500
1455  209152.578125

[1456 rows x 1 columns]

In [89]:
sub_df=submission_df.copy()

In [90]:
sub_df['SalePrice'] = test_preds_df['SalePrice']

In [91]:
idx_rep = [1456,1457,1458]
for i in idx_rep:
    sub_df['SalePrice'].iloc[i] = submission_df['SalePrice'].iloc[i]

/tmp/ipykernel_1794/1570253678.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_df['SalePrice'].iloc[i] = submission_df['SalePrice'].iloc[i]

In [92]:
sub_df.isna().sum()

Id           0
SalePrice    0
dtype: int64

In [93]:
sample_submission = sub_df.copy()
sample_submission.to_csv('sample_submission.csv',index=False)

In [94]:
sample_submission

        Id      SalePrice
0     1461  145064.734375
1     1462  192433.062500
2     1463  193111.343750
3     1464  201146.484375
4     1465  222493.656250
...    ...            ...
1454  2915  156292.812500
1455  2916  209152.578125
1456  2917  219222.423400
1457  2918  184924.279659
1458  2919  187741.866657

[1459 rows x 2 columns]

In [101]:
import joblib
import json

data_columns={ 'operated_columns': {
   "conv_columns":list(modified_train.columns),
  'dummmy_columns':[col for col in X_train.columns if col not in modified_cols and col not in num_cols],
   'scaling_columns':extract_cols
}
}
with open('house_predreg_model.pkl', 'wb') as f:
    joblib.dump(best_estimator, f)
with open('data_columns.json', 'w') as f:
   json.dump(data_columns,f)

In [99]:
import jovian
jovian.commit(filename='house_predreg.ipynb')

[jovian] Updating notebook "mrheaven1y/house-predreg" on https://jovian.com/
[jovian] Committed successfully! https://jovian.com/mrheaven1y/house-predreg

'https://jovian.com/mrheaven1y/house-predreg'

## Done!